class Autogenerated {
  String? paymentId;
  String? paymentMode;
  PaymentCreatedBy? paymentCreatedBy;
  String? isActive;
  bool? status;
  String? sId;
  String? createdAt;
  int? iV;

  Autogenerated(
      {this.paymentId,
        this.paymentMode,
        this.paymentCreatedBy,
        this.isActive,
        this.status,
        this.sId,
        this.createdAt,
        this.iV});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    print(json);
    paymentId = json['payment_id'];
    paymentMode = json['payment_mode'];
    paymentCreatedBy = json['payment_created_by'] != null
        ? new PaymentCreatedBy.fromJson(json['payment_created_by'])
        : null;
    isActive = json['isActive'];
    status = json['status'];
    sId = json['_id'];
    createdAt = json['created_at'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['payment_id'] = this.paymentId;
    data['payment_mode'] = this.paymentMode;
    if (this.paymentCreatedBy != null) {
      data['payment_created_by'] = this.paymentCreatedBy!.toJson();
    }
    data['isActive'] = this.isActive;
    data['status'] = this.status;
    data['_id'] = this.sId;
    data['created_at'] = this.createdAt;
    data['__v'] = this.iV;
    return data;
  }
}

class PaymentCreatedBy {
  String? adminId;
  String? adminName;

  PaymentCreatedBy({this.adminId, this.adminName});

  PaymentCreatedBy.fromJson(Map<String, dynamic> json) {
    adminId = json['admin_id'];
    adminName = json['admin_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['admin_id'] = this.adminId;
    data['admin_name'] = this.adminName;
    return data;
  }
}
