import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:liveretro_project/payment/paycreate.dart';


class turf extends StatefulWidget {
  const turf({super.key});

  @override
  State<turf> createState() => _turfState();
}

class _turfState extends State<turf> {

  final _key = GlobalKey<FormState>();


  TextEditingController box = TextEditingController();

  Future<Autogenerated>? _create;

  Future<Autogenerated> create(String mode) async {
    var resp = await http.post(Uri.parse("http://turf.gtcollege.in/api/payments/create"),

      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, dynamic>{
        "payment_mode": mode,
        "admin_id":"A17",
        "admin_name":"prabha"
      }),
    );
    return Autogenerated.fromJson(jsonDecode(resp.body));
  }

  List data=[];



  bool _isAddingItem = false;

  void _addItemToList() async {
    if (_isAddingItem) {
      return; // If already adding an item, return to avoid multiple calls
    }

    setState(() {
      _isAddingItem = true; // Set the flag to indicate that an item is being added
    });

    String text = box.text;
    if (text.isNotEmpty) {
      try {
        Autogenerated newItem = await create(text);

        setState(() {
          data.add({"Paymentmode": newItem.paymentMode});
          box.clear();
        });

        // Pass the newly added item as a result to the previous screen
        Navigator.of(context).pop({"Paymentmode": newItem.paymentMode});
      } catch (error) {
        print("Error adding item: $error");
      } finally {
        setState(() {
          _isAddingItem = false; // Reset the flag after adding the item
        });
      }
    }
  }


  // String text1="";

  // void delete(index){
  //   setState(() {
  //     data.removeAt(index);
  //   });
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        appBar: AppBar(
          backgroundColor: Colors.white,
          title:Text ("Payment Modes ",style: TextStyle(
              color: Colors.black,
              fontSize: 24,fontFamily:"Outfit",fontWeight:FontWeight.w100),),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              Form(
                key: _key,
                child: Container(
                  height: MediaQuery.of(context).size.height * 0.9,
                  width: MediaQuery.of(context).size.width * 0.9,
                  decoration: BoxDecoration(
                  ),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(20),
                        child: TextFormField(
                            keyboardType: TextInputType.text,
                            style: TextStyle(fontFamily: "Outfit",fontWeight: FontWeight.w100,color: Colors.white),
                            controller: box,
                            decoration: InputDecoration(
                                prefixIcon: Padding(
                                  padding: const EdgeInsets.all(8.0),
                                  child: Icon(Icons.payment,color: Colors.white,),
                                ),
                                labelText: "Enter your Payment mode",
                                labelStyle: TextStyle(fontFamily: "Outfit",fontWeight: FontWeight.w100
                                    ,color: Colors.white)
                            ),
                            validator: (payment)
                            {
                              if (payment == null || payment.isEmpty)
                              {
                                return("Please Enter Your Payment Name");
                              }
                              else if (!RegExp(r'^[a-zA-Z0-9&%=]+$').hasMatch(payment))
                              {
                                return("Please Enter Valid Payment Name");
                              }
                            }
                        ),
                      ),
                      SizedBox(
                        height: 30,
                      ),
                      Padding(
                        child: ElevatedButton(
                          onPressed: () {
                            // _create = create(box.text);
                            if(_key.currentState!.validate()) {
                              setState(() {
                                _addItemToList();
                              });

                            }
                          },
                          child: Text("Save",style: TextStyle(
                            fontFamily: "Outfit",
                            fontWeight: FontWeight.w100,fontSize: 18,
                            color: Colors.black,
                          ),
                          ),
                          style: ElevatedButton.styleFrom(
                              foregroundColor: Colors.white, minimumSize: (Size(150, 50)),
                              // primary: Colors.white,
                              side: BorderSide(width:3, color:Colors.black), //border width and color
                              elevation: 3,
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(20)
                              )
                          ),
                        ),
                        padding: const EdgeInsets.all(8.0),
                      ),

                      // SizedBox(
                      //   height: 300,
                      // ), Container(
                      //   height: 300,
                      //   width: 400,
                      //   decoration: BoxDecoration(
                      //     borderRadius: BorderRadius.circular(15),
                      //     border: Border.all(),
                      //   ),
                      //   child:  ListView.builder(
                      //       itemCount: data.length,
                      //       itemBuilder:(BuildContext context,index){
                      //         return Padding(
                      //           padding: const EdgeInsets.all(8.0),
                      //           child: GestureDetector(
                      //             onTap: (){
                      //             },
                      //             child: Card(
                      //               color: Colors.black,
                      //               child: ListTile(
                      //                 title: Text(data[index],style: TextStyle(color:Colors.white,fontFamily: "Outfit",fontWeight: FontWeight.w100),),
                      //                 trailing: SizedBox(
                      //                   height: 50,
                      //                   width: 70,
                      //                   child: Row(
                      //                     children: [
                      //                       IconButton(onPressed: (){
                      //                         showDialog(context: context,
                      //                             builder: (context)=>SimpleDialog(
                      //                               backgroundColor: Colors.white,
                      //                               children: [
                      //                                 TextFormField(
                      //                                   onChanged: (value){
                      //                                     setState(() {
                      //                                       text1 = value;
                      //                                     });
                      //                                   },
                      //                                   style: TextStyle(color: Colors.white,fontFamily: "Outfit",fontWeight: FontWeight.w100),
                      //                                 ),
                      //                                 ElevatedButton(style: ElevatedButton.styleFrom(
                      //                                     minimumSize: (Size(50, 50)),
                      //                                     primary: Color(0xffde6d11),
                      //                                     onPrimary: Colors.white,
                      //                                     shape: RoundedRectangleBorder()
                      //                                 ),onPressed: (){
                      //                                   setState(() {
                      //                                     Navigator.pop(context);
                      //                                     data [index] = text1;
                      //                                   });
                      //                                 }, child: Text("Update",style: TextStyle(fontWeight: FontWeight.w100,fontFamily: "Outfit"),),)
                      //                               ],
                      //                             ));
                      //                       }, icon:Icon(Icons.edit,color: Colors.white,),),
                      //                       GestureDetector(
                      //                         onTap: (){
                      //                           delete(index);
                      //                         },
                      //                         child: Icon(Icons.delete,color: Colors.white,),
                      //                       ),
                      //                     ],
                      //                   ),
                      //                 ),
                      //               ),
                      //             ),
                      //           ),
                      //         );
                      //       }),
                      // )
                      // Container(
                      //   alignment: Alignment.center,
                      //   child: (_create == null) ? createColumn() :createbuilder()
                      // ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        )
    );
  }
// Column createColumn(){
//   return
//     Column(
//     children: [
//       Form(
//         key: _key,
//         child: Container(
//           height: MediaQuery.of(context).size.height * 0.9,
//           width: MediaQuery.of(context).size.width * 0.9,
//           decoration: BoxDecoration(
//           ),
//           child: Column(
//             mainAxisAlignment: MainAxisAlignment.center,
//             children: [
//               Padding(
//                 padding: const EdgeInsets.all(20),
//                 child: TextFormField(
//                   keyboardType: TextInputType.text,
//                   style: TextStyle(fontFamily: "Outfit",fontWeight: FontWeight.w100,color: Colors.white),
//                   controller: box,
//                   decoration: InputDecoration(
//                       prefixIcon: Padding(
//                         padding: const EdgeInsets.all(8.0),
//                         child: Icon(Icons.payment,color: Colors.white,),
//                       ),
//                       labelText: "Enter your Payment mode",
//                       labelStyle: TextStyle(fontFamily: "Outfit",fontWeight: FontWeight.w100
//                           ,color: Colors.white)
//                   ),
//                   validator: (payment)
//                     {
//                       if (payment == null || payment.isEmpty)
//                         {
//                           return("Please Enter Your Payment Name");
//                         }
//                       else if (!RegExp(r'^[a-zA-Z0-9&%=]+$').hasMatch(payment))
//                         {
//                           return("Please Enter Valid Payment Name");
//                         }
//                     }
//                 ),
//               ),
//               SizedBox(
//                 height: 30,
//               ),
//               Padding(
//                 child: ElevatedButton(
//                   onPressed: () {
//                     if(_key.currentState!.validate()) {
//                       setState(() {
//                         _create = create(box.text);
//                         _addItemToList();
//                       });
//                     }
//                   },
//                   child: Text("Save",style: TextStyle(
//                       fontFamily: "Outfit",
//                       fontWeight: FontWeight.w100,fontSize: 18,
//                       color: Colors.black,
//                   ),
//                   ),
//                   style: ElevatedButton.styleFrom(
//                       minimumSize: (Size(150, 50)),
//                       primary: Colors.white,
//                       onPrimary: Colors.white,
//                       side: BorderSide(width:3, color:Colors.black), //border width and color
//                       elevation: 3,
//                       shape: RoundedRectangleBorder(
//                           borderRadius: BorderRadius.circular(20)
//                       )
//                   ),
//                 ),
//                 padding: const EdgeInsets.all(8.0),
//               ),
//
//               // SizedBox(
//               //   height: 300,
//               // ), Container(
//               //   height: 300,
//               //   width: 400,
//               //   decoration: BoxDecoration(
//               //     borderRadius: BorderRadius.circular(15),
//               //     border: Border.all(),
//               //   ),
//               //   child:  ListView.builder(
//               //       itemCount: data.length,
//               //       itemBuilder:(BuildContext context,index){
//               //         return Padding(
//               //           padding: const EdgeInsets.all(8.0),
//               //           child: GestureDetector(
//               //             onTap: (){
//               //             },
//               //             child: Card(
//               //               color: Colors.black,
//               //               child: ListTile(
//               //                 title: Text(data[index],style: TextStyle(color:Colors.white,fontFamily: "Outfit",fontWeight: FontWeight.w100),),
//               //                 trailing: SizedBox(
//               //                   height: 50,
//               //                   width: 70,
//               //                   child: Row(
//               //                     children: [
//               //                       IconButton(onPressed: (){
//               //                         showDialog(context: context,
//               //                             builder: (context)=>SimpleDialog(
//               //                               backgroundColor: Colors.white,
//               //                               children: [
//               //                                 TextFormField(
//               //                                   onChanged: (value){
//               //                                     setState(() {
//               //                                       text1 = value;
//               //                                     });
//               //                                   },
//               //                                   style: TextStyle(color: Colors.white,fontFamily: "Outfit",fontWeight: FontWeight.w100),
//               //                                 ),
//               //                                 ElevatedButton(style: ElevatedButton.styleFrom(
//               //                                     minimumSize: (Size(50, 50)),
//               //                                     primary: Color(0xffde6d11),
//               //                                     onPrimary: Colors.white,
//               //                                     shape: RoundedRectangleBorder()
//               //                                 ),onPressed: (){
//               //                                   setState(() {
//               //                                     Navigator.pop(context);
//               //                                     data [index] = text1;
//               //                                   });
//               //                                 }, child: Text("Update",style: TextStyle(fontWeight: FontWeight.w100,fontFamily: "Outfit"),),)
//               //                               ],
//               //                             ));
//               //                       }, icon:Icon(Icons.edit,color: Colors.white,),),
//               //                       GestureDetector(
//               //                         onTap: (){
//               //                           delete(index);
//               //                         },
//               //                         child: Icon(Icons.delete,color: Colors.white,),
//               //                       ),
//               //                     ],
//               //                   ),
//               //                 ),
//               //               ),
//               //             ),
//               //           ),
//               //         );
//               //       }),
//               // )
//               // Container(
//               //   alignment: Alignment.center,
//               //   child: (_create == null) ? createColumn() :createbuilder()
//               // ),
//             ],
//           ),
//         ),
//       ),
//     ],
//   );
// }
//   FutureBuilder<Autogenerated> createbuilder() {
//     return FutureBuilder<Autogenerated>(
//         future: _create,
//         builder: (context, snapshot) {
//           if (snapshot.hasData) {
//             if (snapshot.data!.paymentId != null) {
//               Future.delayed(const Duration(milliseconds: 500), () {
//                 setState(() {
//                   // Navigator.pop(context);
//                   Navigator.of(context).pushAndRemoveUntil(
//                       MaterialPageRoute(builder: (context) => second1()),
//                       (route) => false);
//                 });
//               }
//               );
//             } else {
//               return Text(style: TextStyle(color: Colors.white38), "Not Added");
//             }
//             //return Text(snapshot.data!.paymentMode.toString());
//           } else if (snapshot.hasError) {
//             return Text("${snapshot.hasError.toString()}");
//           }
//           return CircularProgressIndicator();
//         });
//   }
}
//
